backend:
  - changed-files:
    - any-glob-to-any-file:
      - "backend/**/*"

build:
  - changed-files:
    - any-glob-to-any-file:
      - "*.mk"
      - "Makefile"
      - "package.json"
      - "package-lock.json"
      - "poetry.lock"
      - "poetry.toml"
      - "pyproject.toml"
      - ".node-version"
      - ".python-version"

ci:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**/*"

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - "package-json.lock"
      - "poetry.lock"
      - ".node-version"
      - ".python-version"

infrastructure:
  - changed-files:
    - any-glob-to-any-file:
      - "infrastructure/**/*"

style:
  - changed-files:
    - any-glob-to-any-file:
      - ".editorconfig"
      - ".flake8"
      - ".pre-commit-config.yaml"
      - "tsconfig.json"

survey:
  - changed-files:
    - any-glob-to-any-file:
      - "survey/**/*"

test:
  - changed-files:
    - any-glob-to-any-file:
      - "backend/tests/**/*"
      - "infrastructure/tests/**/*"
      - "tests/**/*"
      - ".github/workflows/run_cypress.yml"

twilio:
  - changed-files:
    - any-glob-to-any-file:
      - "twilio/**/*"
      - ".github/workflows/flex_admin_deploy.yml"
      - ".github/workflows/twilio_config.yml"
