name: "CI Flex Admin"
description: "Run CI steps for Flex Admin plugin."

inputs:
  twilio-account-sid:
    description: "Twilio Account SID"
    required: true
    type: string
  twilio-auth-token:
    description: "Twilio Auth Token"
    required: true
    type: string

runs:
  using: "composite"
  steps:    
    - name: "Install frontend (twilio/admin/)"
      uses: "./.github/actions/install_frontend/"    
      with:
        install-args: "--legacy-peer-deps"
        install-twilio-cli: "true"
        install-twilio-flex-plugin: "true"
        working-directory: "twilio/admin/"
       
    - name: "Build Flex Admin plugin"
      run: "twilio flex:plugins:build"
      working-directory: "twilio/admin/"
      env:
        TWILIO_ACCOUNT_SID: "${{ inputs.twilio-account-sid }}"
        TWILIO_AUTH_TOKEN: "${{ inputs.twilio-auth-token }}"
      shell: bash                        