name: "Prepare .env.dev.local file"
description: "Prepare DotENV file for backend needs."

inputs:
  aws-access-key-id:
    description: "AWS access key ID to store in DotENV file"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key to store in DotENV file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Create .env.dev.local file"
      shell: "bash"
      run: "make .env.dev.local"

    - name: "Append AWS access key ID & secret access key to .env.dev.local file"
      shell: "bash"
      run: |
        set -euo pipefail

        echo -e "\n# AWS access keys" >> .env.dev.local
        echo "AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}" >> .env.dev.local
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}" >> .env.dev.local

    - name: "Append fake parameter names to .env.dev.local file"
      shell: "bash"
      run: |
        set -euo pipefail

        echo -e "\n# Parameter names" >> .env.dev.local

        for secret_name in OPENAI_API_KEY OPENAI_ORGANIZATION; do
          echo "${secret_name}_PARAMETER_NAME=/neurality-demo/fake-secret/${secret_name}" >> .env.dev.local
        done
