name: "Twilio Configuration"
description: "Configure Twilio Account to use for given stack."

inputs:
  stack-name:
    description: "Configure Twilio for given stack"
    required: true

  account-sid:
    description: "Twilio account SID to use"
    required: true

  api-key:
    description: "Twilio API key to use"
    required: true

  api-secret:
    description: "Twilio API secret to use"
    required: true

  default-phone-number:
    description: "Phone number to use"
    required: true

  default-author-name:
    description: "Author name to use by default"
    required: true

  default-scenario-slug:
    description: "Default scenario slug to use"
    required: false
    default: ""

  boto3-version:
    description: "boto3 version to install"
    required: false
    default: "1.34.158"

  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true

  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true    

runs:
  using: "composite"
  steps:
    - uses: "actions/setup-python@v5.4.0"
      with:
        python-version-file: ".python-version"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1        

    - name: "Install boto3"
      shell: "bash"
      run: "python3 -m pip install boto3==${{ inputs.boto3-version }}"

    - name: "Configure Twilio"
      shell: "python"
      run: |
        import boto3

        dynamodb_client = boto3.client("dynamodb")
        table_name = "${{ inputs.stack-name }}-twilio-configs"

        print(f"DynamoDB table to update: {table_name}")

        account_sid = "${{ inputs.account-sid }}"
        if not account_sid.startswith("AC"):
          account_sid = f"AC{account_sid}"

        extra = {}

        print(
          dynamodb_client.put_item(
            TableName=table_name,
            Item={
              "account_sid": {"S": account_sid},
              "api_key": {"S": "${{ inputs.api-key }}"},
              "api_secret": {"S": "${{ inputs.api-secret }}"},
              "default_phone_number": {"S": "${{ inputs.default-phone-number }}"},
              "default_author_name": {"S": "${{ inputs.default-author-name }}"},
            } | extra,
          )
        )
        print("All OK!")
