name: "Install Frontend"
description: "Install node.js and twilio cli & necessary plugins if required."

inputs:
  install-twilio-cli:
    description: "Install twilio-cli to global scope?"
    required: false
    default: "false"

  install-twilio-flex-plugin:
    description: "Install twilio flex plugin manager?"
    required: false
    default: "false"

  install-twilio-serverless-plugin:
    description: "Install twilio serverless plugin?"
    required: false
    default: "false"

  node-version-file:
    description: "Path to .node-version"
    required: true
    default: ".node-version"

  twilio-cli-version:
    description: "Twilio CLI version to use"
    required: false
    default: "5.22.9"

runs:
  using: "composite"
  steps:
    - name: "Install node.js"
      uses: "actions/setup-node@v4.0.3"
      with:
        node-version-file: "${{ inputs.node-version-file }}"
        cache: "npm"

    - if: "${{ inputs.install-twilio-cli == 'true' }}"
      shell: "bash"
      run: |
        echo "Installing Twilio CLI version: ${{ inputs.twilio-cli-version }}..."
        npm install -g twilio-cli@${{ inputs.twilio-cli-version }}
        echo "Twilio CLI installation completed."

    - if: "${{ inputs.install-twilio-flex-plugin == 'true' }}"
      shell: "bash"
      run: |
        echo "Installing Twilio Flex Plugin Manager..."
        twilio plugins:install @twilio-labs/plugin-flex@7.0.0
        echo "Twilio Flex Plugin Manager installation completed."

    - if: "${{ inputs.install-twilio-serverless-plugin == 'true' }}"
      shell: "bash"
      run: |
        echo "Installing Twilio Serverless Plugin..."
        twilio plugins:install @twilio-labs/plugin-serverless
        echo "Twilio Serverless Plugin installation completed."
