defaults:
  run:
    shell: "bash"

name: "Bump AWS CDK"

on:
  schedule:
    # https://crontab.guru/#0_4_1_*_*
    - cron: "0 4 1 * *"  # At 04:00 on day-of-month 1.
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"

jobs:
  bump_aws_cdk:
    name: "Bump AWS CDK"

    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v4.1.7"

      - name: "Install system packages"
        run: "sudo apt update -y && sudo apt install -y curl jq"

      - uses: "./.github/actions/install_backend/"

      - id: "bump-aws-cdk"
        name: "Run bump AWS CDK script"
        run: "./.github/scripts/bump-aws-cdk.sh"

      - id: "token"
        if: "${{ steps.bump-aws-cdk.outputs.latest-version }}"
        uses: "tibdex/github-app-token@v2.1.0"
        with:
          app_id: "${{ secrets.BADABUMP_APP_ID }}"
          private_key: "${{ secrets.BADABUMP_APP_PRIVATE_KEY }}"

      - name: "Create pull request with changed files"
        if: "${{ steps.bump-aws-cdk.outputs.latest-version }}"
        uses: "peter-evans/create-pull-request@v7.0.6"
        with:
          token: "${{ steps.token.outputs.token }}"
          commit-message: |
            build(deps): Bump aws-cdk-lib from ${{ steps.bump-aws-cdk.outputs.current-version }} to ${{ steps.bump-aws-cdk.outputs.latest-version }}

            - [Release notes](https://github.com/aws/aws-cdk/releases/tag/v${{ steps.bump-aws-cdk.outputs.latest-version }})
            - [Commits](https://github.com/aws/aws-cdk/compare/v${{ steps.bump-aws-cdk.outputs.current-version }}...v${{ steps.bump-aws-cdk.outputs.latest-version }})
          branch: "build/aws-cdk-lib-${{ steps.bump-aws-cdk.outputs.latest-version }}"
          delete-branch: true
          title: "build(deps): Bump aws-cdk-lib from ${{ steps.bump-aws-cdk.outputs.current-version }} to ${{ steps.bump-aws-cdk.outputs.latest-version }}"
          body: |
            - [Release notes](https://github.com/aws/aws-cdk/releases/tag/v${{ steps.bump-aws-cdk.outputs.latest-version }})
            - [Commits](https://github.com/aws/aws-cdk/compare/v${{ steps.bump-aws-cdk.outputs.current-version }}...v${{ steps.bump-aws-cdk.outputs.latest-version }})
          labels: "build,dependencies,infrastructure"
