defaults:
  run:
    shell: "bash"

name: "Distribute New Customer Standup Tasks"

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer name'
        required: true
      env:
        description: 'Environment type'
        required: true
        type: "choice"
        options:
          - "Stage"
          - "Prod"

run-name: "New Customer Standup Tasks: ${{ inputs.customer }}.${{ inputs.env }} "

jobs:
  generate:
    runs-on: "ubuntu-22.04"

    steps:
    - uses: "actions/checkout@v4.1.7"

    - id: "python"
      uses: "actions/setup-python@v5.2.0"
      with:
        python-version-file: ".python-version"

    - name: "Install dependencies"
      run: "python3 -m pip install requests"

    - name: "Create Tickets"
      run: python scripts/gh_standup.py "${{ inputs.customer }}" "${{ inputs.env }}"
