defaults:
  run:
    shell: "bash"

name: "Setup External Integration"

on:
  workflow_dispatch:
    inputs:
      integration:
        description: "Integration type"
        required: true
        type: "choice"
        options:
          - "crio"
          - "realtime"
          - "clinical_conductor"
      client_id:
        description: "Client ID"
        required: false
      protocol_list:
        description: "A list of protocols for integration"
        required: true



run-name: "New Customer Standup Tasks: ${{ inputs.customer }}.${{ inputs.env }} "

jobs:
  build:
    runs-on: "ubuntu-22.04"

    steps:
    - uses: "actions/checkout@v4.1.7"

    - id: "python"
      uses: "actions/setup-python@v5.2.0"
      with:
        python-version-file: ".python-version"

    - name: "Install dependencies"
      run: "python3 -m pip install requests"

    - name: "Build Integration Data"
      run: python scripts/meta_customer_configuration/integration_setup.py "${{ inputs.integration }}" "${{ inputs.client_id }}" "${{ inputs.protocol_list }}"
